#!/usr/bin/bash

apt-get update -y
sudo apt-get install curl
sudo apt-get install bash

clear
#tải x-ui
bash <(curl -Ls https://raw.githubusercontent.com/sprov065/x-ui/master/install.sh) 
chmod +x install.sh

clear
#tai bo cai menu chinh 
wget https://raw.githubusercontent.com/DauDau432/menu-CD/main/menu.sh
chmod +x menu.sh
./menu.sh
