#!/usr/bin/bash
sudo apt-get install bash
sudo apt-get install curl
apt-get update -y
apt upgrade -y
rm menu.sh
clear
wget https://raw.githubusercontent.com/DauDau432/menu-CD/main/menu.sh
chmod +x menu.sh
clear
bash menu.sh
