#!/usr/bin/bash



apt-get update -y
sudo apt-get install curl
sudo apt-get install bash

clear
#tải x-ui
bash <(curl -Ls https://raw.githubusercontent.com/sprov065/x-ui/master/install.sh) 
chmod +x install.sh

clear
#meu x-ui
bash <( -Ls https://raw.githubusercontent.com/DauDau432/menu-CD/main/menu_x-ui.sh )
chmod +x menu_x-ui.sh 

clear
#menu chinh 
bash <( curl -Ls https://raw.githubusercontent.com/DauDau432/menu-CD/main/CD_menu.sh )
chmod +x CD_menu.sh
./CD_menu.sh
